#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : util-macros
Version  : 1.19.0
Release  : 3
URL      : http://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.gz
Summary  : A set of autoconf project macros for X.Org modules
Group    : Development/Tools
License  : MIT
Requires: util-macros-data

%description
This is a set of autoconf macros used by the configure.ac scripts in
other Xorg modular packages, and is needed to generate new versions
of their configure scripts with autoconf.

%package data
Summary: data components for the util-macros package.
Group: Data

%description data
data components for the util-macros package.


%package dev
Summary: dev components for the util-macros package.
Group: Development
Requires: util-macros-data

%description dev
dev components for the util-macros package.


%prep
%setup -q -n util-macros-1.19.0

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/util-macros/INSTALL

%files dev
%defattr(-,root,root,-)
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4
